#@TYPE: Machine
#@NAME: Beacon i.MX 8M Plus Development Kit
#@SOC: i.MX8MM
#@DESCRIPTION: Machine configuration for Beacon i.MX 8M Plus Development Kit
#@MAINTAINER: Adam Ford <aford@beaconembedded.com>

require include/imx8mp-beacon-kit.inc
require conf/machine/include/moal.inc

# The device tree name is implicit for LPDDR4, so can't use MACHINE here
KERNEL_DEVICETREE_BASENAME = "imx8mp-beacon-kit"

# NXP kernel has additional DTB files for various board configuration and
# derivates. Include them here for NXP BSP only
KERNEL_DEVICETREE:append:use-nxp-bsp = " \
    freescale/${KERNEL_DEVICETREE_BASENAME}-dual-basler.dtb \
    freescale/imx8mp-beacon-spidev.dtb \
"

UBOOT_CONFIG_BASENAME = "imx8mp_beacon"
UBOOT_CONFIG[fspi] = "${UBOOT_CONFIG_BASENAME}_defconfig"

# Set DDR FIRMWARE
DDR_FIRMWARE_VERSION = "202006"
DDR_FIRMWARE_NAME = " \
    lpddr4_pmu_train_1d_dmem_${DDR_FIRMWARE_VERSION}.bin \
    lpddr4_pmu_train_1d_imem_${DDR_FIRMWARE_VERSION}.bin \
    lpddr4_pmu_train_2d_dmem_${DDR_FIRMWARE_VERSION}.bin \
    lpddr4_pmu_train_2d_imem_${DDR_FIRMWARE_VERSION}.bin \
"

IMXBOOT_TARGETS_BASENAME = "flash_evk"

# Mainline BSP doesn't support LPDDR4 so it must be set to nxp.
# Also this machine isn't supported by u-boot-fslc but imx8mn-evk.inc already
# set the bootloader to u-boot-imx instead when NXP BSP is used.
IMX_DEFAULT_BSP = "nxp"

WKS_FILE_DEPENDS:append:beacon-imx8mp-kit = " imx-m7-demos"
IMAGE_BOOT_FILES:append:beacon-imx8mp-kit = " \
    mcore-demos/imx8mp_m7_TCM_hello_world.bin \
    mcore-demos/imx8mp_m7_TCM_low_power_wakeword.bin \
    mcore-demos/imx8mp_m7_TCM_rpmsg_lite_pingpong_rtos_linux_remote.bin \
    mcore-demos/imx8mp_m7_TCM_rpmsg_lite_str_echo_rtos.bin \
    mcore-demos/imx8mp_m7_TCM_sai_low_power_audio.bin \
"
