#@TYPE: Machine
#@NAME: Beacon i.MX 8M Mini Development Kit
#@SOC: i.MX8MM
#@DESCRIPTION: Machine configuration for Beacon i.MX 8M Mini Development Kit
#@MAINTAINER: Adam Ford <aford@beaconembedded.com>

require include/imx8mm-beacon-kit.inc

KERNEL_DEVICETREE_BASENAME = "imx8mm-beacon-kit"
#KERNEL_DEVICETREE:append:use-nxp-bsp = " \
#    freescale/${KERNEL_DEVICETREE_BASENAME}-lvds.dtb \
#    freescale/${KERNEL_DEVICETREE_BASENAME}-spidev.dtb \
#"

UBOOT_CONFIG_BASENAME = "imx8mm_beacon"
UBOOT_CONFIG[fspi] = "${UBOOT_CONFIG_BASENAME}_fspi_defconfig"

DDR_FIRMWARE_NAME = " \
    lpddr4_pmu_train_1d_imem.bin \
    lpddr4_pmu_train_1d_dmem.bin \
    lpddr4_pmu_train_2d_imem.bin \
    lpddr4_pmu_train_2d_dmem.bin \
"

IMXBOOT_TARGETS_BASENAME = "flash_evk"

IMX_DEFAULT_BSP = "nxp"
