#@TYPE: Machine
#@NAME: Beacon Embedded Works NXP i.MX 93
#@SOC: i.MX93
#@DESCRIPTION: Machine configuration for Beacon Embedded Works NXP i.MX 93 Kit
#@MAINTAINER: Beacon Embedded Works

MACHINEOVERRIDES =. "mx93:"

require include/imx93-beacon-kit.inc

DISTRO_NAME = "Beacon i.MX Release Distro"

KERNEL_DEVICETREE = " \
    freescale/imx93-beacon-kit.dtb \
    freescale/imx93-beacon-kit-5.5.dtb \
    freescale/imx93-beacon-kit-10.1.dtb \
"

KERNEL_DTB = "imx93-beacon-kit.dtb"

UBOOT_DTB_NAME = "imx93-beacon-kit.dtb"
UBOOT_CONFIG_BASENAME = "imx93_beacon"

DDR_FIRMWARE_NAME = " \
    lpddr4_dmem_1d_v202201.bin \
    lpddr4_dmem_2d_v202201.bin \
    lpddr4_imem_1d_v202201.bin \
    lpddr4_imem_2d_v202201.bin \
"

IMXBOOT_TARGETS = "flash_singleboot"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS += "kernel-image kernel-devicetree"

MACHINE_FEATURES:append = " dpdk rdp nxpwifi-all-sdio 00363 00365 "
MACHINE_FIRMWARE:append = " ethos-u-firmware ap1302-firmware linux-firmware-rtl-nic "

WKS_FILE = "imx-beacon-boot-bootpart.wks.in"

# This SOM uses a different EEPROM format than other Beacon boards
IMAGE_INSTALL:remove = "beacon-eeprom-decoder beacon-eeprom-services"
