# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

IMAGE_INSTALL:append = "\
	sdma \
	libcamera-gst \
	libcamera-pycamera \
		 "
KERNEL_MODULE_AUTOLOAD += "sdma"

LAYERSERIES_COMPAT_meta-beacon-nxp = "styhead walnascar"
LICENSE_FLAGS_ACCEPTED = "commercial"
